name: Release
on: [workflow_dispatch] # Manual trigger
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: openjdk:16-jdk
      options: --user root
    steps:
      - run: apt-get install git # We need git so that git metadata is preserved
      - uses: actions/checkout@v2 # Required for indra-git
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew checkVersion build publish -stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
