name: Test
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        # Keep the matrix for when jdk 17 rc come out
        java: [16-jdk]
    runs-on: ubuntu-20.04
    container:
      image: openjdk:${{ matrix.java }}
      options: --user root
    steps:
      - run: apt install git # We need git so that git metadata is preserved
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew check build publishToMavenLocal --stacktrace
      #- run: mkdir run && echo "eula=true" >> run/eula.txt
      #- run: ./gradlew :runAutoTestServer --stacktrace
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./*/build/libs/
